### PR TITLE
add filter with users' id for more safe.

### PR DESCRIPTION
**Pull request by tgly307**
I found that the allowed_users function has a flaw: other user can use the unauthorized command by modifying the his username. This situation can be avoided by using user ID filtering. This way is more secure in a multi-user environment.

### CODE REVIEW

**Comment by attzonko** [comment]
I get the issue you are trying to prevent.

I was just thinking about this, would it make more sense to update the existing function to look up the user_id and compare it with the user_id from the message. If they don't match deny the request? Would that make more sense? 

The current solution seems a bit awkward to use, you would need to know the user_ids for the users you want to allow.

**Comment by seLain** [comment]
@tgly307 I tried username changing on MM. 
It seems that if the new username is occupied by another user, this request will be denied by MM.
So this issue only happens when one user gives up his current username, and there's another user takes that username. Am I right ?

How about limit allowed users by email ?  The user email can be got by `message.get_user_email()` in handler, and by clicking user icon on MM channel.

**Comment by tgly307** [comment]
@attzonko What you said makes sense. The purpose of my initial writing is to add another restriction method without changing the original code. At present, the method of updating the original function should be more elegant. It seems that I should change my mind about overprotecting the original code.
Using user_id to confirm permissions should be the most restrictive, although it is not very convenient to use, perhaps I think too much, if the administrator can update the relevant information in time, this problem can be avoided.

@seLain Thanks for reminding. I tried again, the mm server will reject the request when the user has already used the username. I also tried to modify the email address, and the modification conditions are the same as the username. However, the possibility of modifying the email address under normal circumstances should be much smaller than modifying the username. This method should work, I will change this function to yours.

**Comment by attzonko** [comment]
Can you update the docs with an example of how someone would use this with usernames/emails?

@seLain Does it make sense to update the unit test mock_plugin.py for this change?

**Comment by tgly307** [comment]
@attzonko 
I think the current mock_plugin.py is not valid for testing the allowed_users function, because the user information of the driver is not passed to the function unless the driver is called admin or root. I will try to fix it.

**Comment by seLain** [comment]
@attzonko I think the allow/disallow tests should belong to behavior tests. I actually worked on this today. @tgly307 I sent a PR (tgly307/mmpy_bot#2) to your repo, please check it out. The PR includes a test for current @allowed_users decorator. You can improve it to whatever tests necessary.

**Comment by tgly307** [comment]
@seLain I merge your PR, but I don't know where the test bot load `test_plugins`. I am so confused with writing tests.

**Comment by tgly307** [comment]
I am so sad that I still have no idea about how the test works.

**Comment by seLain** [comment]
@tgly307 I am already working on a branch to improve testing modules. 

The improvement goals include:
- increase testing coverage
- improve test code structure
- document to extend tests

But I can't promise when it will be done.

Maybe you can implement and document whatever you want to improve first, and I can help with the test part later if that's ok for you.

**Comment by tgly307** [comment]
@seLain Thank you very much, this is really a big help.

**Comment by tgly307** [comment]
I will close this PR first to roll back code. When I finish, I will open a new one.

**Pull request closed without merging**
