### PR TITLE
hotfix: removing MATTERMOST_API_PATH settings

### PR DESCRIPTION
**Pull request by aminiun**
Hi!

Apparently, `mattermostautodriver` package is not accepting `base_path` as a setting anymore. (I don't know why really).

So when we have this default setting, the final API path would be `/api/v4/api/v4/users/me` which fails. So my project is broken now and pls consider this PR as a hotfix.

### CODE REVIEW

**Comment by unode** [comment]
The explanation on why `base_path` is no longer effective can be found [in this commit description](https://github.com/embl-bio-it/python-mattermost-autodriver/commit/b86773798c56607d14b7e8584350b1db56b88a7b).

As the author of that change, I can confirm that this PR is needed for mmpy_bot but likely we will want to do some version pinning along with it.

In hindsight, as this can be seen as an API change, I should have likely done a major rather than a patch release of `mattermostautodriver`. Apologies for that.

**Comment by unode** [comment]
I'll merge this as-is but changes are needed also on documentation.
Similarly as people may have `MATTERMOST_API_PATH` configured, we should bump at least the [MINOR version digit](https://semver.org/#summary).

The meaning of `MATTERMOST_API_PATH` also changed as it is now only relevant if the mattermost server is running from a subfolder rather than at domain level (e.g. `example.com/mattermost/` instead of `mattermost.example.com`).

However, since `MATTERMOST_URL` already allows this, I would actually deprecate and propose removing `MATTERMOST_API_PATH` altogether. Due to the upstream changes, it is no longer a useful setting. @attzonko what would you say?

**Comment by aminiun** [comment]
As you said, people may have `MATTERMOST_API_PATH`.

Removing it would be a cost for them, as they should remove the arg from their codes.

I suugest lets just not to pass `basepath` to `Driver` class, so user settings on `MATTERMOST_API_PATH` would be ignored and no changes need by them.

**Comment by unode** [comment]
Yes, we wouldn't remove the setting straight away but deprecate it.

On a different topic, looks like most integration tests are failing. Not clear why yet but I wonder if there's a missing `/` in the URL path concatenation. @aminiun would you be able to look into this?

**Comment by aminiun** [comment]
I found the bug finally.

It in the `mattermostdriver` repo, I will make a PR there...

**Comment by unode** [comment]
> I found the bug finally.
> 
> It in the `mattermostdriver` repo, I will make a PR there...

I believe I may have found the same bug that you did.
Meanwhile, I removed release `mattermostautodriver` 1.2.4 and pushed 1.3.0.

See also #431 for the proposed fix.

**Pull request closed without merging**
