### PR TITLE
modify API to support message with attachments, add info to README.md

### PR DESCRIPTION
**Pull request by tgly307**

### CODE REVIEW

**Comment by attzonko** [comment]
Thanks for the contribution @tgly307 , can you add a test for this API under the tests folder?

**Comment by tgly307** [comment]
oh I forget this, I will add test later.

**Comment by tgly307** [comment]
@attzonko Hi, I found [this case](https://github.com/attzonko/mmpy_bot/blob/d2fe9fa39ef9b92e8376883cacb4258fc5f92ab3/tests/unit_tests/local_plugins/hello.py#L35) will use 'get incoming hooks' API, should I need to add another one?

**Comment by attzonko** [comment]
That should work :)

**Pull request merged**
