### PR TITLE
add python 3 judge

### PR DESCRIPTION
**Pull request by tgly307**
try to judge python version

### CODE REVIEW

**Comment by tgly307** [comment]
#50 try to avoid python version error in future, but I don't think this is a long-term solution. We need to decide when we no longer support python 2.

**Comment by seLain** [comment]
`importlib.util.find_spec(name, package=None)` is new in Python 3.4

Would it be better cheking version by `sys.version > '3.4'` ?

**Comment by tgly307** [comment]
@seLain yes, you're right.

**Comment by attzonko** [comment]
I am not a big fan of this pull request. We are doing things in a way that is not very "_pythonic_". We are creating a function to tell us if the python version is '3' however our threshold is really '3.4' simply because of the _imp_ module deprecation timeframe. The whole direction of checking the current version seems wrong and not very scalable. I am a big proponent of asking for forgiveness not permission. For example could we do something like (untested):
```
try:
    from imp import find_module
except ImportError:
   from importlib.abc import find_module
```
And then change the existing code from doing _imp.find_module_ to just _find_module_?

**Comment by tgly307** [comment]
@attzonko Thank you for reminding. I really don't like this kind of code style, and I have neglected to use the threshold before. Compatibility handling, especially for compatibility across large versions, is very difficult. Keep the current state for the time being, wait for future solutions.

**Pull request closed without merging**
