### PR TITLE
Removed Team ID

### PR DESCRIPTION
**Pull request by sunnythaper**
API v4 no longer has a Team ID.

### CODE REVIEW

**Comment by attzonko** [comment]
Can you help me understand what this means or point me to some documentation where they communicated that team_id is not part of API V4?

I just tested the default `!info` plugin and it is still able to get a TEAM-ID back.

**Comment by sunnythaper** [comment]
Weird, I don't have the exact error message but when I copied and pasted
that code, the error message specifically called out that Team-ID is no
longer available in v4. Maybe tomorrow I can try to repeat it to get the
exact error. All I did was remove that line and it worked great for me.

**Comment by attzonko** [comment]
Are you trying this in a direct message? Or as part of a Public/Private Channel?

**Comment by sunnythaper** [comment]
I've tried all three just to make sure. Same error in all three cases.

**Comment by attzonko** [comment]
This is weird, we no longer have MattermostAPIv4 object. Is this with latest repo or pypi module?

**Comment by sunnythaper** [comment]
You know what, I didn't consider my docker image was old but I have been using this as it was the latest Dockerfile I could find for mmpy_bot:

https://github.com/Celforyon/mmbot

**Comment by attzonko** [comment]
I was not aware a docker image existed, thanks for the heads up.

**Pull request closed without merging**
