### PR TITLE
fix error when handle bad command.

### PR DESCRIPTION
**Pull request by tgly307**

### CODE REVIEW

**Comment by attzonko** [comment]
Thanks for finding and fixing this. Is there some test we can add to catch stuff like this in the future?

**Comment by tgly307** [comment]
In fact, I am not good at writing test cases, I feel that the existing test cases are comprehensive enough. Perhaps due to the historical reasons of this project, some code is still in a stage that is not fully understood, and we can gradually comb the old code to add unit tests. After all, this project does not exist as commercial software, we can slowly find the problem.  XD

**Comment by attzonko** [comment]
Totally agree, was just wondering if this issue might be an easy one to add a test case for, and since you hit it and fixed it you might be the best to answer that question. I'll have to think more about your Python version question. I was hoping that we can continue to support both, meaning to be backwards compatible if possible.

**Comment by seLain** [comment]
@tgly307  Could you share us more how you bumped into this error ? There might be clue for constructing adequate test cases.

**Comment by tgly307** [comment]
@seLain I want to modify default response content, before I start this work, I tried to entered a wrong command to see how this function work.

**Comment by tgly307** [comment]
@attzonko OK, got it. But the execfile() function is not support in python 3, although this code will rarely execute，I think it needs to be version compatible here to avoid error like this issue .

**Pull request merged**
