### PR TITLE
feat: upload file & reply message with file, add email to allowed_users filter

### PR DESCRIPTION
**Pull request by tgly307**
Upload file API can be used by `message.upload_file(file)`, this function's return information contain file ID if everything goes well. And I add a parameter `files(array)` in `message.reply` function to reply message with files by use file ID.

Add email to allow_users filter to provide more choice to admin user.

### CODE REVIEW

**Comment by seLain** [comment]
Thanks for the effort @tgly307. 
I will try to accomplish the review and test code this weekend.

**Comment by tgly307** [comment]
@seLain Thx help. 
Here is an example plugin I test this function.
```
@respond_to('file$', re.IGNORECASE)
@listen_to('file$', re.IGNORECASE)
def get_test_file(message):
    file = open('test.txt', 'w+')
    result = message.upload_file(file)
    file.close()
    if 'file_infos' not in result:
        message.reply('upload file error')
    file_id = result['file_infos'][0]['id']
    message.reply('hello', [file_id])
```
Hope this can help your work

**Comment by seLain** [comment]
@tgly307  I sent a PR to your repo with fix and tests. Please check it out.
Also, please consider update `mmpy_bot\docs` as well. thanks.

**Comment by tgly307** [comment]
@seLain thanks for help.

**Pull request merged**
