### PR TITLE
(feat): add getting picture or other file public link in posted message

### PR DESCRIPTION
**Pull request by tgly307**
with this feature, the bot can handle the file in posted message. For example, submit picture to some API to search similar pictures.

### CODE REVIEW

**Comment by attzonko** [comment]
Looks good to me. Thanks for updating the tests.

**Comment by seLain** [comment]
Hi, sorry for the late review.

I got error running the test code : 
```
Traceback (most recent call last):
  File "C:\py36_venv\mmpy_bot\lib\site-packages\mmpy_bot-1.2.0-py3.6.egg\mmpy_bot\dispatcher.py", line 78, in dispatch_msg
    func(Message(self._client, msg, self._pool), *args)
  File "C:\GitHub\mmpy_bot\tests\test_runpy\local_plugins\hello.py", line 23, in search_picture
    file_link = message.get_file_link(file_id)
AttributeError: 'Message' object has no attribute 'get_file_link'
```
According to committed code, there were only ``get_file_link`` API added to ``MattermostAPIv4`` class, and ``get_file_link`` function added to ``MessageDispatcher`` class. There was no ``Message.get_file_link`` behavior.

I am not sure which one is correct. The test code or the committed code  ?

Also, I think it would be better putting ``search_picture`` test code in an independent plugin module. Maybe ``unit_tests\local_plugins\picture.py`` ?

**Comment by attzonko** [comment]
Thanks for checking @seLain. I am in the process of creating a mattermost team instance for testing. Hopefully I can have the tests run for each commit to avoid this in the future. 

@tgly307 Can you comment on which is correct the test code or the committed code? I am assuming the committed code is correct. Would you be open to moving the test for this into a separate module as suggested?

**Comment by tgly307** [comment]
@attzonko Oh sorry, I just saw this.  I will check this later.

**Pull request merged**
