### PR TITLE
Pytest coverage

### PR DESCRIPTION
**Pull request by seLain**
- Fixed relative importing issue to enable pytest-coverage
- Add `test coverage section` in README.md
- All test cases passed

### CODE REVIEW

**Comment by seLain** [comment]
I am not sure how to pass the travis CI build test :disappointed: 
It seemed that pytest can not make success connection by default MM user account setting ?

**Comment by attzonko** [comment]
Looking into it now

**Comment by attzonko** [comment]
This is the issue: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

Need to figure out how we want to solve it. It does not like that the pull request comes from a forked version of the repo. So it removed all the encrypted settings for the build.

**Comment by attzonko** [comment]
OK I decided to just leave those variables open. I don't think it should be a problem. We will not be able to test the 'admin only' tests

**Comment by attzonko** [comment]
Looks like you have a merge conflict?

**Pull request merged**
