### PR TITLE
Implement PluginManager and HelpPlugin

### PR DESCRIPTION
**Pull request by unode**
This is an attempt to split #226 into smaller PRs, easier to review.
This PR should be merged after #323 and #325.

### CODE REVIEW

**Comment by unode** [comment]
I don't think I can get rid of the 2 codeclimate issues without making the code harder to read.
@attzonko do you think this is acceptable?

Also I ended up re-merging the two features in one PR as I couldn't get everything to validate and tests to pass in the in-between state and it was becoming too time consuming.

Black was also bumped in this PR as I couldn't run the previous version locally.

**Comment by attzonko** [comment]
@unode Please check to make sure my conflict resolution in function.py did not break anything for you.

Otherwise I think we can squash and merge this.

**Comment by attzonko** [comment]
@unode Ok I think I fixed the mess :) Can you verify that the commit makes sense to you? https://github.com/attzonko/mmpy_bot/pull/326/commits/f0a703983f8d881823b7ac54fedfb07356d5fa2e

**Comment by attzonko** [comment]
As all the tests passed, I am pretty sure it is correct, will go ahead and merge.

**Pull request merged**
